/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package disenio.generico;

import modelo.SistemaFederacionJudo;
import modelo.administracion_registro.Domicilio;
import modelo.administracion_registro.Persona;
import modelo.administracion_registro.Usuario;

/**
 *
 * @author Alumno
 */
public class DatosPersonalesJFrame extends javax.swing.JFrame {

    private String conAsteriscos ="";
    private Usuario sesion;
    private Persona datos;
    private Domicilio dom;
    
    public DatosPersonalesJFrame(Usuario u) {
        initComponents();
        sesion = u;
        
        tipo.setText(tipo.getText() + u.getTipoUsuario().toString());
        nomUsuario.setText(nomUsuario.getText() + u.getNickName());
        
        for(int i=0;i<u.getContraseña().length();i++){
        
            conAsteriscos+= "* ";
        }
        contraseña.setText("Contraseña: " + conAsteriscos);
        datos = new SistemaFederacionJudo().cargarPersona(u);
        dom = datos.getDomicilio();
        dni.setText("DNI: " + datos.getDni().toString());
        nombre.setText("Nombre: " + datos.getNombre());
        apellido1.setText("Primer apellido: " + datos.getApellido1());
        apellido2.setText("Segundo apellido: " + datos.getApellido2());
        fNacimiento.setText("Fecha de nacimiento: " + datos.getFechaNacimiento().toString());
        sexo.setText("Sexo: " + datos.getSexo().toString());
        direccion.setText("Direccion: " + dom.getDIRECCION());
        cp.setText("Codigo postal: " + dom.getCODIGO_POSTAL());
        municipio.setText("Municipio: " + dom.getMUNICIPIO());
        provincia.setText("Provincia: " + dom.getPROVINCIA());
        
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        nomUsuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        dni = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido1 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JLabel();
        fNacimiento = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        municipio = new javax.swing.JLabel();
        provincia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Datos personales");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(118, 118, 118))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 516, 80));

        jButton3.setText("Volver");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        nomUsuario.setForeground(new java.awt.Color(0, 0, 0));
        nomUsuario.setText("Nombre de usuario: ");
        jPanel5.add(nomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 220, 30));

        contraseña.setForeground(new java.awt.Color(0, 0, 0));
        contraseña.setText("Contraseña: ");
        jPanel5.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, -1));

        tipo.setForeground(new java.awt.Color(0, 0, 0));
        tipo.setText("Tipo de usuario: ");
        jPanel5.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 119, 260, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ver-contraseña.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jButton4.setText("Cambiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        dni.setForeground(new java.awt.Color(0, 0, 0));
        dni.setText("DNI: ");
        jPanel5.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 150, -1));

        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setText("Nombre: ");
        jPanel5.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 220, -1));

        apellido1.setForeground(new java.awt.Color(0, 0, 0));
        apellido1.setText("Primer apellido: ");
        jPanel5.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 320, -1));

        apellido2.setForeground(new java.awt.Color(0, 0, 0));
        apellido2.setText("Segundo apellido: ");
        jPanel5.add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, -1));

        fNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        fNacimiento.setText("Fecha de nacimiento: ");
        jPanel5.add(fNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 290, -1));

        sexo.setForeground(new java.awt.Color(0, 0, 0));
        sexo.setText("Sexo: ");
        jPanel5.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 240, -1));

        direccion.setForeground(new java.awt.Color(0, 0, 0));
        direccion.setText("Direccion: ");
        jPanel5.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 280, -1));

        cp.setForeground(new java.awt.Color(0, 0, 0));
        cp.setText("Código postal: ");
        jPanel5.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, -1));

        municipio.setForeground(new java.awt.Color(0, 0, 0));
        municipio.setText("Municipio: ");
        jPanel5.add(municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 220, -1));

        provincia.setForeground(new java.awt.Color(0, 0, 0));
        provincia.setText("Provincia: ");
        jPanel5.add(provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed

    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        contraseña.setText("Contraseña: " + sesion.getContraseña());
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased

        contraseña.setText("Contraseña: " + conAsteriscos);
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        CambiarContraseñaJDialog cCJD = new CambiarContraseñaJDialog(this,true,sesion);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido1;
    private javax.swing.JLabel apellido2;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel cp;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel dni;
    private javax.swing.JLabel fNacimiento;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel municipio;
    private javax.swing.JLabel nomUsuario;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel provincia;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
